---
proxy-providers:
  Akun_ID:
    type: http
    path: "./proxy_provider/AXIS GAME.yaml"
    url: https://raw.githubusercontent.com/Koswara1985/OpenWrt/main/AXIS GAME.yaml
    interval: 28800 # Update rules every 8 hours
    health-check:
      enable: true
      url: https://cp.cloudflare.com/generate_204
      interval: 10

proxy-groups:

- name: VPN 🌎
  type: select
  disable-udp: false
  proxies:
  - Url-Test🔰
  - Pilih🔰
  url: https://cp.cloudflare.com/generate_204
  interval: '10'
  tolerance: '10'

- name: Url-Test🔰
  type: url-test
  disable-udp: false
  use:
  - Akun_ID
  url: https://cp.cloudflare.com/generate_204
  interval: '10'
  tolerance: '10'

- name: Pilih🔰
  type: select
  disable-udp: false
  use:
  - Akun_ID
  url: https://cp.cloudflare.com/generate_204
  interval: '10'
  tolerance: '10'

port: 7890
socks-port: 7891
redir-port: 7892
mixed-port: 7893
tproxy-port: 7895
ipv6: false
mode: rule
log-level: silent
allow-lan: true
external-controller: 0.0.0.0:9090
secret: ""
bind-address: "*"
unified-delay: true
profile:
  store-selected: true
dns:
  enable: true
  ipv6: false
  enhanced-mode: redir-host
  listen: 0.0.0.0:7874
  nameserver:
    - 8.8.8.8
    - 1.0.0.1
    - https://dns.google/dns-query
  fallback:
    - 1.1.1.1
    - 8.8.4.4
    - https://cloudflare-dns.com/dns-query
    - 112.215.203.254
  default-nameserver:
    - 8.8.8.8
    - 1.1.1.1
    - 112.215.203.254
rules:
  - MATCH,VPN 🌎